version: '3.9'

services:
  node:
    image: ghcr.io/meerugin/ddd/index:1.1
    restart: unless-stopped
    container_name: ddd/index

  python:
    image: ghcr.io/meerugin/ddd/main:1.1
    restart: unless-stopped
    container_name: ddd/main
