version: '3'
services:
  node:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./nodejs:/app
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python:/app
